# .properties는 계층구조의 중복 발생 한다.
# yml, yaml을 통해 들여쓰기 계층구조 사용

# port 번호 변경시, default는 8080
#server:
#  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
